const matchData = [
    {
        date: "2024-10-20",
        teams: "Orange Horses vs BLACK DOG",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "192/7 (20.0 ov) & 115/10 (16.0 ov)",
        result: "Orange Horses won by 77 runs",
        stage:"Final",
      },
      {
        date: "2024-10-19",
        teams: "Orange Horses vs Purple Panthers",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "183/7 (20.0 ov) & 120/10 (15.5 ov)",
        result: "Orange Horses won by 63 runs",
        stage:"Semi-Final"
      },
      {
        date: "2024-10-18",
        teams: "BLACK DOG vs Purple Panthers",
        venue: "One7sports Park, Gurugram (Gurgaon)",
        scores: "232/7 (20.0 ov) & 222/5 (20.0 ov)",
        result: "BLACK DOG won by 10 runs",
        stage:"Semi-Final"
      },
      {
        date: "2024-10-18",
        teams: "White TIGERS vs Orange Horses",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "191/8 (20.0 ov) & 192/6 (19.0 ov)",
        result: "Orange Horses won by 4 wickets",
        stage:"Quarter Finals"
      },
      {
        date: "2024-10-18",
        teams: "Orange Horses vs White TIGERS",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "192/6 (19.0 ov) & 191/8 (20.0 ov)",
        result: "Orange Horses won by 4 wickets",
        stage:"Quarter Finals"
      },
      {
        date: "2024-10-15",
        teams: "Purple Panthers vs Brown Bears",
        venue: "One7sports Park, Gurmatkal",
        scores: "",
        result: "Purple Panthers won by walkover",
                stage:"Quarter Finals"
      },
      {
        date: "2024-10-15",
        teams: "White TIGERS vs Red Bulls",
        venue: "Leg Stump, One7 Sports Park, Gurugram (Gurgaon)",
        scores: "229/8 (20.0 ov) & 111/8 (19.2 ov)",
        result: "White TIGERS won by 118 runs",
                stage:"Quarter Finals"
      },
      {
        date: "2024-10-10",
        teams: "Green Sharks vs Blue Scorpions",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "192/7 (20.0 ov) & 157/10 (19.4 ov)",
        result: "Green Sharks won by 35 runs",
      },
      {
        date: "2024-10-10",
        teams: "Yellow Lion vs Blue Scorpions",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "151/5 (12.3 ov) & 148/7 (20.0 ov)",
        result: "Yellow Lion won by 5 wickets",
      },
      {
        date: "2024-10-08",
        teams: "BLACK DOG vs White TIGERS",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "188/7 (20.0 ov) & 161/7 (20.0 ov)",
        result: "BLACK DOG won by 27 runs",
      },
      {
        date: "2024-10-08",
        teams: "Red Bulls vs Green Sharks",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "205/5 (20.0 ov) & 164/7 (17.1 ov)",
        result: "Red Bulls won by 41 runs (All out)",
      },
      {
        date: "2024-10-06",
        teams: "Yellow Lion vs Orange Horses",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "142/4 (12.3 ov) & 139/8 (20.0 ov)",
        result: "Yellow Lion won by 6 wickets",
      },
      {
        date: "2024-10-06",
        teams: "Yellow Lion vs Orange Horses",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "142/4 (12.3 ov) & 139/8 (20.0 ov)",
        result: "Yellow Lion won by 6 wickets",
      },
      {
        date: "2024-10-05",
        teams: "BLACK DOG vs Brown Bears",
        venue: "Leg Stump, One7 Sports Park, Gurugram (Gurgaon)",
        scores: "205/3 (20.0 ov) & 179/9 (18.2 ov)",
        result: "BLACK DOG won by 26 runs (All out)",
      },
      {
        date: "2024-10-02",
        teams: "White TIGERS vs Blue Scorpions",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "145/9 (19.0 ov) & 231/3 (20.0 ov)",
        result: "Blue Scorpions won by 86 runs",
      },
      {
        date: "2024-10-02",
        teams: "Purple Panthers vs Yellow Lion",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "141/6 (19.2 ov) & 139/7 (20.0 ov)",
        result: "Purple Panthers won by 2 wickets",
      },
      {
        date: "2024-10-02",
        teams: "Yellow Lion vs Green Sharks",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "148/2 (13.1 ov) & 146/10 (17.1 ov)",
        result: "Yellow Lion won by 8 wickets",
      },
      {
        date: "2024-09-29",
        teams: "Yellow Lion vs Grey elephant",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "209/6 (20.0 ov) & 205/5 (20.0 ov)",
        result: "Yellow Lion won by 4 wickets",
      },
      {
        date: "2024-09-28",
        teams: "Brown Bears vs Red Bulls",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "135/4 (13.3 ov) & 132/9 (20.0 ov)",
        result: "Brown Bears won by 6 wickets",
      },
      {
        date: "2024-09-28",
        teams: "Green Sharks vs White TIGERS",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "203/6 (20.0 ov) & 204/5 (20.0 ov)",
        result: "White TIGERS won by 5 wickets",
      },
      {
        date: "2024-09-28",
        teams: "White TIGERS vs Green Sharks",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "204/5 (20.0 ov) & 203/6 (20.0 ov)",
        result: "White TIGERS won by 5 wickets",
      },
      {
        date: "2024-09-28",
        teams: "BLACK DOG vs Orange Horses",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "170/5 (20.0 ov) & 178/9 (20.0 ov)",
        result: "Orange Horses won by 8 runs",
      },
      {
        date: "2024-09-25",
        teams: "White TIGERS vs Grey elephant",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "161/9 (18.5 ov) & 157/10 (19.1 ov)",
        result: "White TIGERS won by 1 wicket",
      },
      {
        date: "2024-09-25",
        teams: "Green Sharks vs Purple Panthers",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "192/7 (20.0 ov) & 188/2 (17.4 ov)",
        result: "Purple Panthers won by 8 wickets",
      },
    
     
    
      {
        date: "2024-09-25",
        teams: "Green Sharks vs Blue Scorpions",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "192/7 (20.0 ov) & 157/10 (19.4 ov)",
        result: "Green Sharks won by 35 runs",
      },
      {
        date: "2024-09-24",
        teams: "Purple Panthers vs BLACK DOG",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "181/4 (18.2 ov) & 177/8 (20.0 ov)",
        result: "Purple Panthers won by 6 wickets",
      },
      {
        date: "2024-09-22",
        teams: "Red Bulls vs Grey elephant",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "143/6 (17.2 ov) & 139/9 (20.0 ov)",
        result: "Red Bulls won by 4 wickets",
      },
      {
        date: "2024-09-22",
        teams: "Orange Horses vs White TIGERS",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "173/6 (20.0 ov) & 176/5 (16.2 ov)",
        result: "White TIGERS won by 5 wickets",
      },
    
      {
        date: "2024-09-21",
        teams: "Purple Panthers vs Green Sharks",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "188/2 (17.4 ov) & 187/8 (20.0 ov)",
        result: "Purple Panthers won by 8 wickets",
      },
      {
        date: "2024-09-19",
        teams: "Brown Bears vs Grey elephant",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "250/6 (20.0 ov) & 213/5 (20.0 ov)",
        result: "Brown Bears won by 37 runs",
      },
      {
        date: "2024-09-19",
        teams: "Orange Horses vs Green Sharks",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "136/9 (20.0 ov) & 72/10 (14.5 ov)",
        result: "Orange Horses won by 64 runs",
      },
      {
        date: "2024-09-17",
        teams: "Purple Panthers vs Blue Scorpions",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "132/5 (16.1 ov) & 131/10 (19.3 ov)",
        result: "Purple Panthers won by 5 wickets",
      },
    
      {
        date: "2024-09-22",
        teams: "White TIGERS vs Orange Horses",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "176/5 (16.2 ov) & 173/6 (20.0 ov)",
        result: "White TIGERS won by 5 wickets",
      },
      {
        date: "2024-09-22",
        teams: "Blue Scorpions vs Brown Bears",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "175/5 (18.5 ov) & 173/8 (20.0 ov)",
        result: "Blue Scorpions won by 5 wickets",
      },
      {
        date: "2024-09-21",
        teams: "BLACK DOG vs Yellow Lion",
        venue: "One7 Sports Park Off Stump, Gurugram (Gurgaon)",
        scores: "175/5 (14.3 ov) & 173/10 (19.5 ov)",
        result: "BLACK DOG won by 5 wickets",
      },
      {
        date: "2024-09-21",
        teams: "Green Sharks vs Purple Panthers",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "187/8 (20.0 ov) & 188/2 (17.4 ov)",
        result: "Purple Panthers won by 8 wickets",
      },
     
      
    {
      date: "2024-08-28",
      teams: "Orange Horses vs Red Bulls",
      venue: "One7 Sports Park, Gurmatkal",
      scores: "142/10 (19.1 ov) & 73/9 (20.0 ov)",
      result: "Orange Horses won by 69 runs",
    },
    {
      date: "2024-08-28",
      teams: "Grey elephant vs Purple Panthers",
      venue: "One7 Sports Park, Gurugram (Gurgaon)",
      scores: "177/4 (18.0 ov) & 176/5 (20.0 ov)",
      result: "Grey elephant won by 6 wickets",
    },
    {
      date: "2024-08-24",
      teams: "Purple Panthers vs Red Bulls",
      venue: "One7 Sports Park, Gurmatkal",
      scores: "101/2 (16.3 ov) & 98/10 (19.5 ov)",
      result: "Purple Panthers won by 8 wickets",
    },
    {
      date: "2024-08-24",
      teams: "White Tigers vs Yellow LION",
      venue: "One7 Sports Park, Gurugram (Gurgaon)",
      scores: "132/2 (17.0 ov) & 128/10 (14.1 ov)",
      result: "White Tigers won by 4 wickets",
    },
    {
        date: "2024-09-17",
        teams: "Purple Panthers vs Blue Scorpions",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "132/5 (16.1 ov) & 131/10 (19.3 ov)",
        result: "Purple Panthers won by 5 wickets",
      },
      {
        date: "2024-09-17",
        teams: "BLACK DOG vs Red Bulls",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "206/8 (20.0 ov) & 175/8 (20.0 ov)",
        result: "BLACK DOG won by 31 runs",
      },
      {
        date: "2024-09-15",
        teams: "BLACK DOG vs Grey elephant",
        venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
        scores: "135/6 (16.4 ov) & 134/10 (20.0 ov)",
        result: "BLACK DOG won by 4 wickets",
      },
      {
        date: "2024-09-15",
        teams: "Brown Bears vs Yellow Lion",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "150/7 & 9/0 (0.3 ov) & 150/9 & 8/2 (1.0 ov)",
        result: "Match abandoned", // Assuming the match was abandoned due to rain
      },
      {
        date: "2024-09-03",
        teams: "Orange Horses vs Blue Scorpions",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "172/5 (16.1 ov) & 168/8 (20.0 ov)",
        result: "Orange Horses won by 5 wickets",
      },
      {
        date: "2024-09-01",
        teams: "Brown Bears vs Orange Horses",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "148/5 (19.5 ov) & 147/4 (20.0 ov)",
        result: "Brown Bears won by 5 wickets",
      },
      {
        date: "2024-09-01",
        teams: "Purple Panthers vs White TIGERS",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "139/8 (19.2 ov) & 138/10 (17.3 ov)",
        result: "Purple Panthers won by 2 wickets",
      },
      {
        date: "2024-09-01",
        teams: "Red Bulls vs Yellow Lion",
        venue: "One7 Sports Park, Gurugram (Gurgaon)",
        scores: "151/10 (19.5 ov) & 167/7 (20.0 ov)",
        result: "Yellow Lion won by 16 runs",
      },

  {
    date: "2024-09-15",
    teams: "Yellow Lion vs Brown Bears",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "150/7 & 9/0 (0.3 ov) & 150/9 & 8/2 (1.0 ov)",
    result: "Match Tied (Yellow Lion won the super over)",
  },
  {
    date: "2024-09-15",
    teams: "Orange Horses vs Purple Panthers",
    venue: "One7 Sports Park Middle Stump, Gurugram (Gurgaon)",
    scores: "191/6 (20.0 ov) & 136/10 (18.2 ov)",
    result: "Orange Horses won by 55 runs",
  },
  {
    date: "2024-09-11",
    teams: "Grey elephant vs Green Sharks",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "169/10 (19.5 ov) & 168/10 (20.0 ov)",
    result: "Grey elephant won by 1 run",
  },
  {
    date: "2024-09-10",
    teams: "Yellow Lion vs Purple Panthers",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "139/7 (20.0 ov) & 141/6 (19.2 ov)",
    result: "Purple Panthers won by 2 wickets",
  },

  {
    date: "2024-09-10",
    teams: "Purple Panthers vs Yellow Lion",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "141/6 (19.4 ov) & 139/7 (20.0 ov)",
    result: "Purple Panthers won by 4 wickets",
  },
  {
    date: "2024-09-10",
    teams: "White TIGERS vs Brown Bears",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "181/6 (20.0 ov) & 106/10 (14.2 ov)",
    result: "White TIGERS won by 75 runs",
  },
  {
    date: "2024-09-10",
    teams: "Red Bulls vs Blue Scorpions",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "132/2 (14.4 ov) & 127/10 (16.4 ov)",
    result: "Red Bulls won by 8 wickets",
  },
  {
    date: "2024-09-03",
    teams: "Orange Horses vs Blue Scorpions",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "172/5 (16.1 ov) & 168/8 (20.0 ov)",
    result: "Orange Horses won by 5 wickets",
  },
  
  {
    date: "2024-08-24",
    teams: "White TIGERS vs Yellow Lion",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "132/2 (14.1 ov) & 128/10 (17.0 ov)",
    result: "White TIGERS won by 8 wickets",
  },
  {
    date: "2024-08-24",
    teams: "Green Sharks vs Brown Bears",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "159/9 (20.0 ov) & 152/9 (20.0 ov)",
    result: "Green Sharks won by 7 runs",
  },
  {
    date: "2024-08-24",
    teams: "BLACK DOG vs Blue Scorpions",
    venue: "One7sports Park, Gurmatkal",
    scores: "160/8 (20.0 ov) & 155/7 (20.0 ov)",
    result: "BLACK DOG won by 5 runs",
  },
  {
    date: "2024-08-24",
    teams: "Orange Horses vs Grey elephant",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "150/4 (17.4 ov) & 149/10 (20.0 ov)",
    result: "Orange Horses won by 1 run",
  },
  {
    date: "2024-09-01",
    teams: "Yellow Lion vs Red Bulls",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "167/7 (20.0 ov) & 151/10 (19.5 ov)",
    result: "Yellow Lion won by 16 runs",
  },
  {
    date: "2024-08-31",
    teams: "Grey elephant vs Blue Scorpions",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "178/8 (19.5 ov) & 177/10 (20.0 ov)",
    result: "Grey elephant won by 2 wickets",
  },
  {
    date: "2024-08-31",
    teams: "BLACK DOG vs Green Sharks",
    venue: "One7 Sports Park, Gurugram (Gurgaon)",
    scores: "191/9 (20.0 ov) & 161/8 (20.0 ov)",
    result: "BLACK DOG won by 30 runs",
  },
  {
    date: "2024-08-28",
    teams: "Orange Horses vs Red Bulls",
    venue: "One7sports Park, Gurmatkal",
    scores: "142/10 (19.1 ov) & 73/9 (20.0 ov)",
    result: "Orange Horses won by 69 runs",
  },
  
];

export default matchData;